title: Sunset
hero_image: images/banner.png
description: Create a city scene!
listed: false
pdf: false
steps:
  - title: What you will make
  - title: Move the sun
  - title: Make it grow
  - title: Change the colour
  - title: Night sky
  - title: Light it
  - title: Switch cities
  - title: Travel the world
  - title: Where are we?
  - title: Visual first
  - title: Challenge
    challenge: true
    completion:
      - external
