title: Project title in sentence case
hero_image: images/banner.png
description: A short description of the project
listed: false
pdf: false
steps:
  - title: What you will make
  - title: Moving the sun
  - title: Size of sun
  - title: Red sky at night
  - title: The midnight hour
  - title: City lights
  - title: Which city?
  - title: Travel the world
  - title: Where am I?
  - title: Challenge
    challenge: true
    completion:
      - external
