title: Sunset
hero_image: images/banner.png
description: Watch the sunrise and sunset in cities across the world!
listed: false
pdf: resources/sunset-visual.pdf
steps:
  - title: What you will make
  - title: Move the sun
  - title: Make it grow
  - title: Change the colour
  - title: Night sky
  - title: Light it
  - title: Switch cities
  - title: Travel the world
  - title: Where are we?
  - title: Challenge
    challenge: true
    completion:
      - external
  - title: Visual first
