title: Project title in sentence case
hero_image: images/banner.png
description: A short description of the project
listed: false
pdf: false
steps:
  - title: What you will make
  - title: Step 1
  - title: Step 2
  - title: Step 3
  - title: Step 4
  - title: Step 5
  - title: Step 6
  - title: Step 7
  - title: Step 8   
  - title: Challenge
    challenge: true
    completion:
      - external
